#pragma once

enum EventCategory {
    pitch_video,
    novelty,
    content,
    finances,
    deep_dive_topic,
    demonstration_and_structure,
    delivery,
    questions,
    general_impression,
    format_and_accuracy_of_documents,
    knowledge_of_documents_and_vehicle,
    BOM_discussion,
    cost_understanding,
    real_case,
    overall_vehicle_concept,
    vehicle_performance,
    mechanical_structural_engineering,
    tractive_system,
    electronics,
    driver_interface,
    autonomous_functionality,
    design_report,
    first_skid_left_time,
    first_skid_right_time,
    second_skid_left_time,
    second_skid_right_time,
    first_acc_time,
    second_acc_time,
    first_aut_time,
    second_aut_time,
    third_aut_time,
    fourth_aut_time,
    end_corrected_time,
    end_uncorrected_time,
    end_energy_used,
    end_energy_produced,
    tra_time,
    tra_laps,
    cost_and_manufacturing_finals_score,
    businessplan_finals_score,
};

enum EventType {
    acceleration,
    acceleration_DV,
    acceleration_DC,
    autocross,
    autocross_DC,
    businessplan,
    cost_and_manufacturing,
    endurance,
    efficiency,
    engineering_design,
    engineering_design_DC,
    skidpad,
    skidpad_DV,
    skidpad_DC,
    trackdrive,
};

enum LapTimeMode {
    m,
    s,
    ms,
};

enum CompetitionType {
    FSG,
    FSA,
    FSCH,
    FSE,
    FSN,
};